[project]
name = "badminton"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gspread>=6.1.3",
    "oauth2client>=4.1.3",
    "plotly>=5.24.1",
    "streamlit>=1.39.0",
]
